const INCREMENT = 0;
const DECREMENT = 1;
const NEW_BOARD = 3;
const NEW_TODO = 4;
const TOGGLE_TODO = 5;
const NEW_LIST = 6;
const BOARD_TITLE = 7;
const DELETE_LIST = 8;
const DELETE_BOARD = 9;
const DELETE_COMPLETED = 10;

export { DECREMENT, INCREMENT, NEW_BOARD, NEW_TODO, TOGGLE_TODO, NEW_LIST, BOARD_TITLE, DELETE_LIST, DELETE_BOARD, DELETE_COMPLETED };